# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Worktree environment manager — isolated ports, databases, and services across parallel development environments"
  homepage "https://github.com/git-treeline/cli"
  version "0.41.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/git-treeline/cli/releases/download/v0.41.0/cli_0.41.0_darwin_amd64.tar.gz"
      sha256 "30c6629e4186f6334df9ef0640b04d8f28e415aa3db750f3f580c005e5e46b9b"

      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/git-treeline/cli/releases/download/v0.41.0/cli_0.41.0_darwin_arm64.tar.gz"
      sha256 "1d161f14a93fb79d468caa7d1d9d41bae6aca30778e5b7dc5fba42eca497f856"

      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-treeline/cli/releases/download/v0.41.0/cli_0.41.0_linux_amd64.tar.gz"
      sha256 "f4aae067d8f52cae67df933ff7d1005350b8941b458b7d23036aa3ebf7c17db7"
      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-treeline/cli/releases/download/v0.41.0/cli_0.41.0_linux_arm64.tar.gz"
      sha256 "2898c9118790c69660084b73cc1e40444b98713c78619d9a74102d0a345c1b7c"
      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
  end

  def post_install
    # If the user previously installed the HTTPS router service, bounce it
    # so the launchd-managed process picks up the new gtl binary. The
    # --if-installed flag makes this a no-op for users who never ran
    # 'gtl serve install', so first-time brew installs stay quiet.
    system bin/"gtl", "serve", "restart", "--if-installed"
  end

  def caveats
    <<~EOS
      Get started:
        cd your-project && gtl install

      One command: config, hooks, ports, env, and optional HTTPS routing.
      Docs: https://git-treeline.dev/docs/getting-started/
    EOS
  end
end
