# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Worktree environment manager — isolated ports, databases, and services across parallel development environments"
  homepage "https://github.com/git-treeline/cli"
  version "0.39.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/git-treeline/cli/releases/download/v0.39.4/cli_0.39.4_darwin_amd64.tar.gz"
      sha256 "2ccf749859db1469ad5299058829034cced871e5d61cbbd0a9bcd11b2afc43e3"

      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/git-treeline/cli/releases/download/v0.39.4/cli_0.39.4_darwin_arm64.tar.gz"
      sha256 "6deeaa536e384dedd025ac07e8d87b634636cd41ef4d340e72d53b308e2fdb46"

      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-treeline/cli/releases/download/v0.39.4/cli_0.39.4_linux_amd64.tar.gz"
      sha256 "51bfcc9ede55c00a5877befa9ab44223f87170668633127455795661a7c273ba"
      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-treeline/cli/releases/download/v0.39.4/cli_0.39.4_linux_arm64.tar.gz"
      sha256 "2fc084359a182dcda8928014ba5f81cd1985d03a119432bb9ccdbe87cc2c14e3"
      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
  end

  def caveats
    <<~EOS
      Get started:
        cd your-project && gtl install

      One command: config, hooks, ports, env, and optional HTTPS routing.
      Docs: https://git-treeline.dev/docs/getting-started/
    EOS
  end
end
