# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitTreeline < Formula
  desc "Worktree environment manager — isolated ports, databases, and services across parallel development environments"
  homepage "https://github.com/git-treeline/cli"
  version "0.43.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/git-treeline/cli/releases/download/v0.43.0/git-treeline_0.43.0_darwin_amd64.tar.gz"
      sha256 "693b0329530ef6072585c3c2e417a675c244f121737f9d4d359f1c68ab93cabf"

      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/git-treeline/cli/releases/download/v0.43.0/git-treeline_0.43.0_darwin_arm64.tar.gz"
      sha256 "08f1ef1f8c45ded82fc30bd0cf942d46247b4b5fa2fbb3ce8783cd17bebf0b9c"

      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-treeline/cli/releases/download/v0.43.0/git-treeline_0.43.0_linux_amd64.tar.gz"
      sha256 "b3f195721d2ec189890f7375c8d18ef6d9f7168d1f6f7d2651ff07e017723a11"
      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-treeline/cli/releases/download/v0.43.0/git-treeline_0.43.0_linux_arm64.tar.gz"
      sha256 "aa91d491e12231a607e92bacaa13cbab108349a07669f9fcf06055b7b4d2af4e"
      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
  end

  def post_install
    # If the user previously installed the HTTPS router service, bounce it
    # so the launchd-managed process picks up the new gtl binary. The
    # --if-installed flag makes this a no-op for users who never ran
    # 'gtl serve install', so first-time brew installs stay quiet.
    system bin/"gtl", "serve", "restart", "--if-installed"
  end

  def caveats
    <<~EOS
      Get started:
        cd your-project && gtl install

      One command: config, hooks, ports, env, and optional HTTPS routing.
      Docs: https://git-treeline.dev/docs/getting-started/
    EOS
  end
end
