# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitTreeline < Formula
  desc "Worktree environment manager — isolated ports, databases, and services across parallel development environments"
  homepage "https://github.com/git-treeline/cli"
  version "0.43.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/git-treeline/cli/releases/download/v0.43.16/git-treeline_0.43.16_darwin_amd64.tar.gz"
      sha256 "59fedb4567cbfbf0d155f29c99f63c157d6a3f8d8ac870b217ec1fc27322ad86"

      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/git-treeline/cli/releases/download/v0.43.16/git-treeline_0.43.16_darwin_arm64.tar.gz"
      sha256 "cad6c40dbfd0683fdc61114cce3c2359b19930476d3eccb6cc5e3a130559ccbb"

      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-treeline/cli/releases/download/v0.43.16/git-treeline_0.43.16_linux_amd64.tar.gz"
      sha256 "64a49d6be7c59a9a5f1c7fbc8efa24dabae5f15414d012198827abfc8cd6a490"
      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-treeline/cli/releases/download/v0.43.16/git-treeline_0.43.16_linux_arm64.tar.gz"
      sha256 "f97f2be22bf7d5fb27de56899247b176564c399b3b0a4067ac7056eeb8bd60c8"
      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
  end

  def post_install
    # If the user previously installed the HTTPS router service, bounce it
    # so the launchd-managed process picks up the new gtl binary. The
    # --if-installed flag makes this a no-op for users who never ran
    # 'gtl serve install', so first-time brew installs stay quiet.
    system bin/"gtl", "serve", "restart", "--if-installed"
  end

  def caveats
    <<~EOS
      Get started:
        cd your-project && gtl install

      One command: config, hooks, ports, env, and optional HTTPS routing.
      Docs: https://git-treeline.dev/docs/getting-started/
    EOS
  end
end
