# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitTreeline < Formula
  desc "Worktree environment manager — isolated ports, databases, and services across parallel development environments"
  homepage "https://github.com/git-treeline/cli"
  version "0.43.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/git-treeline/cli/releases/download/v0.43.6/git-treeline_0.43.6_darwin_amd64.tar.gz"
      sha256 "1fa3d9abd49284268e50e015d86194722d777f1ab902a8a56b7f11dc5acb537b"

      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/git-treeline/cli/releases/download/v0.43.6/git-treeline_0.43.6_darwin_arm64.tar.gz"
      sha256 "e979b5fee80384e9f9da5a82a01e51728b794f17e3e28163b489bb956e0754bc"

      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-treeline/cli/releases/download/v0.43.6/git-treeline_0.43.6_linux_amd64.tar.gz"
      sha256 "f5cb07e9f8517a4d3fd8b10389f7d3e0fb3a44ed74dd62c8825893ea8f482aa1"
      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-treeline/cli/releases/download/v0.43.6/git-treeline_0.43.6_linux_arm64.tar.gz"
      sha256 "b9d698c43b36877d09237d9c6e6ad21a9be05e92d7555093863481404f2891b0"
      define_method(:install) do
        bin.install "git-treeline"
        bin.install_symlink "git-treeline" => "gtl"

        generate_completions_from_executable(bin/"git-treeline", "completion")
        generate_completions_from_executable(bin/"git-treeline", "completion", base_name: "gtl")
      end
    end
  end

  def post_install
    # If the user previously installed the HTTPS router service, bounce it
    # so the launchd-managed process picks up the new gtl binary. The
    # --if-installed flag makes this a no-op for users who never ran
    # 'gtl serve install', so first-time brew installs stay quiet.
    system bin/"gtl", "serve", "restart", "--if-installed"
  end

  def caveats
    <<~EOS
      Get started:
        cd your-project && gtl install

      One command: config, hooks, ports, env, and optional HTTPS routing.
      Docs: https://git-treeline.dev/docs/getting-started/
    EOS
  end
end
